SmartSparking/SmartSparking/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('web.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

SmartSparking/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.IndexView.as_view()),
    path('empresa/',views.EmpresaView.as_view()),
    path('empresa/<int:empresa_id>',views.EmpresaDetailView.as_view()),
    path('estacionamiento/',views.EstacionamientoView.as_view()),
    path('estacionamiento/<int:estacionamiento_id>',views.EstacionamientoDetailView.as_view()),
    path('estado/',views.EstadoView.as_view()),
    path('estado/<int:estado_id>',views.EstadoDetailView.as_view()),
]

SmartSparking/web/urls.py
from django.urls import path
from . import views 

app_name = 'smartparking'  # Reemplaza "nombre_de_tu_aplicacion" con el nombre real de tu aplicación

urlpatterns = [
    path('estacionamiento/', views.lista_estacionamientos, name='estacionamientos'),
    path('estados_estacionamiento/<int:estacionamiento_id>/', views.estados_estacionamiento, name='estados_estacionamiento'),
    path('empresas/', views.empresas, name='empresas'),

    path('login/', views.login_view, name="login"),
    
    path('about/',views.about,name="about"),
    path('logout/', views.logout_view, name="logout"),

    path('',views.home, name='home')
]

SmartSparking/api/models.py
from django.db import models

# Create your models here.

SmartSparking/web/models.py
from django.db import models
from datetime import time

class Empresa(models.Model):
    nombre = models.CharField(max_length=255)
    correo = models.CharField(max_length=255)
    clave = models.CharField(max_length=255)
    capacidad = models.IntegerField()

    def __str__(self):
        return f"Empresa: {self.nombre} - Capacidad: {self.capacidad}"


class Estacionamiento(models.Model):
    id_empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    lugar = models.CharField(max_length=255)
    estado = models.BooleanField(default=False)

    def __str__(self):
        if self.estado:
            return f"Estacionamiento {self.lugar} - Disponible"
        else:
            return f"Estacionamiento {self.lugar} - Ocupado"


class Estado(models.Model):
    id_estacionamiento = models.ForeignKey(Estacionamiento, on_delete=models.CASCADE, related_name='estados')
    hora_ingreso = models.TimeField()
    hora_salida = models.TimeField()

    def __str__(self):
        if self.hora_salida == time(0, 0):
            return f"Hora de Ingreso: {self.hora_ingreso}"
        else:
            return f"Hora de Salida: {self.hora_salida}"

SmartSparking/api/views.py
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.views import APIView
from web.models import Empresa,Estacionamiento,Estado
from .serializers import(
    EmpresaSerializer,
    EstacionamientoSerializer,
    EstadoSerializer,
)
    
class IndexView(APIView):
    
    def get(self, request):
        lista_empresas = Empresa.objects.all()
        data = [{'id': empresa.id, 'nombre': empresa.nombre, 'correo': empresa.correo, 'clave': empresa.clave} for empresa in lista_empresas]
        return Response(data)
    
class EmpresaView(generics.ListCreateAPIView):
    queryset = Empresa.objects.all()
    serializer_class = EmpresaSerializer
    
class EmpresaDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Empresa.objects.all()
    lookup_url_kwarg = 'empresa_id'
    serializer_class = EmpresaSerializer

class EstacionamientoView(generics.ListCreateAPIView):
    queryset = Estacionamiento.objects.all()
    serializer_class = EstacionamientoSerializer
    
class EstacionamientoDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Estacionamiento.objects.all()
    lookup_url_kwarg = 'estacionamiento_id'
    serializer_class = EstacionamientoSerializer

class EstadoView(generics.ListCreateAPIView):
    queryset = Estado.objects.all()
    serializer_class = EstadoSerializer
    
class EstadoDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Estado.objects.all()
    lookup_url_kwarg = 'estado_id'
    serializer_class = EstadoSerializer

SmartSparking/web/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Empresa, Estacionamiento, Estado
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache


def lista_estacionamientos(request):
    estacionamientos = Estacionamiento.objects.all()
    return render(request, 'into.html', {'estacionamientos': estacionamientos})

def estados_estacionamiento(request, estacionamiento_id):
    estacionamiento = Estacionamiento.objects.get(id=estacionamiento_id)
    estados = Estado.objects.filter(estacionamiento=estacionamiento)
    return render(request, 'estados_estacionamiento.html', {'estacionamiento': estacionamiento, 'estados': estados})

def empresas(request):
    empresas = Empresa.objects.all()
    return render(request, 'empresas.html', {'empresas': empresas})

def login_view(request):
    if request.method == 'POST':
        correo = request.POST['username']
        clave = request.POST['password']

        try:
            empresa = Empresa.objects.get(correo=correo)
            if empresa.clave == clave:
                estacionamientos = Estacionamiento.objects.all()
                return render(request, 'into.html', {'estacionamientos': estacionamientos})
            else:
                # La clave es incorrecta, mostrar un mensaje de error
                messages.error(request, 'La clave ingresada es incorrecta.')
        except Empresa.DoesNotExist:
            # No se encontró ninguna empresa con el correo ingresado, mostrar un mensaje de error
            messages.error(request, 'No existe una cuenta asociada a ese correo.')

    # Si el usuario ya ha iniciado sesión y trata de acceder a la página de inicio de sesión, redirigirlo a la página de inicio
    if request.user.is_authenticated:
        return redirect('smartparking:home')

    return render(request, 'login.html')

@login_required(login_url='smartparking:login')
def into(request):
    return render(request, 'into.html')

@never_cache
def logout_view(request):
    logout(request)
    return redirect('smartparking:login')

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

SmartSparking/web/templates/estacionamientos.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Lista de estacionamientos</title>
</head>
<body>
    <h1>Lista de estacionamientos</h1>
    <ul>
        {% for estacionamiento in estacionamientos %}
        <li>
            <strong>Lugar:</strong> {{ estacionamiento.lugar }}<br>
            <strong>Estado:</strong> {{ estacionamiento.estado }}
        </li>
        {% endfor %}
    </ul>
    
</body>
</html>

SmartSparking/web/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>navbar Tres</title>
    <link rel="stylesheet" href="{% static '/css/index-home.css' %}">
    <link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css' %}">
</head>
<body>
    <header class="header">
        <div class="icono-menu">
            <img src="https://cdn.discordapp.com/attachments/759170694910705677/1120484064953110648/open-menu.png"  id="icono-menu" alt="Logo de la marca">
        </div>
        <div class="cont-menu active" id="menu">
            <ul>
                <li><a href="/login">Login</a></li>
                <li><a href="#">Support</a></li>
                <li><a href="#">Contact Us</a></li>
                </ul>
        </div>  
        <nav>
            <ul class="nav-links">
            </ul>    
        </nav>
    </header>
    <div class="autos">
        <img src="https://cdn.discordapp.com/attachments/759170694910705677/1120484063019552928/auto1.png" alt="autoport">
    </div>
    <div class="textMid">
        <span class="start">El mejor cuidado </span><br>
        <span class="mid"> para tu </span><br>
        <span class="end">Vehiculo</span><br>
        <a class="btn" href="#"><button>contactanos</button></a>
    </div>
    <script>
        const iconoMenu = document.querySelector('#icono-menu');
        const menu = document.querySelector('#menu');

        iconoMenu.addEventListener('click', (e) => {
            // Alternamos estilos para el menú body
            menu.classList.toggle('active');
            document.body.classList.toggle('opacity');

            // Alternamos su atributo 'src' para que el icono de menú cambie
            const rutaActual = e.target.getAttribute('src');

            if (rutaActual == 'https://cdn.discordapp.com/attachments/759170694910705677/1120484064953110648/open-menu.png') {
                e.target.setAttribute('src', 'https://cdn.discordapp.com/attachments/759170694910705677/1120484065150251058/open-menu2.png');
            } else {
                e.target.setAttribute('src', 'https://cdn.discordapp.com/attachments/759170694910705677/1120484064953110648/open-menu.png');
            }
        });
    </script>
</body>
</html>

SmartSparking/web/templates/into.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>INTO</title>
    <link rel="stylesheet" href="{% static '/css/index-into.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css' %}"
    />
  </head>

  <body>
    
    <header class="header">
      <div class="icono-menu">
        <img
          src="https://cdn.discordapp.com/attachments/759170694910705677/1120484064953110648/open-menu.png"
          id="icono-menu"
          alt="Logo de la marca"
        />
      </div>
      <nav>
        <ul class="nav-links"></ul>
      </nav>
      <div class="cont-menu active" id="menu">
        <ul>
          <li><a href="{% url 'smartparking:logout' %}">Cerrar sesión</a></li>
          <li><a href="#">Support</a></li>
        </ul>
      </div>
    </header>

    <!-- Cuerpo -->
    <div class="container">
      <!-- Barra lateral -->
      <aside class="sidebar">
        <h2>Espacios</h2>
        <ul>
          {% for estacionamiento in estacionamientos %}
          <li>
            <strong>{{ estacionamiento.lugar }}</strong> <br>
            {% if estacionamiento.estado %}
                Disponible
            {% else %}
                Ocupado
            {% endif %}
          </li>
          {% endfor %}
       </ul>
      </aside>

      <!-- Contenido principal -->
      <div class="content">
        <div class="image-container">
          <img
            src="https://cdn.discordapp.com/attachments/759170694910705677/1120530726702551071/fondo.png"
            alt="autoport"
          />
          <div class="rectangle-container">
            {% for estacionamiento in estacionamientos %}
              <div class="rectangle {% if estacionamiento.estado %}green{% endif %}"></div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <!-- Flotador -->

    <!-- Script para mostrar la hora actual y cambiar el color del rectángulo -->
    <script>
     
      function updateCurrentTime() {
        var currentTime = new Date();
        var hours = currentTime.getHours();
        var minutes = currentTime.getMinutes();
        var seconds = currentTime.getSeconds();

        // Formato de 2 dígitos para horas, minutos y segundos
        hours = ("0" + hours).slice(-2);
        minutes = ("0" + minutes).slice(-2);
        seconds = ("0" + seconds).slice(-2);

        var timeString = hours + ":" + minutes + ":" + seconds;
        document.getElementById("current-time").textContent = timeString;
      }

      const iconoMenu = document.querySelector("#icono-menu");
      const menu = document.querySelector("#menu");

      iconoMenu.addEventListener("click", (e) => {
        // Alternamos estilos para el menú
        menu.classList.toggle("active");
        document.body.classList.toggle("opacity");
      });
      function actualizarPagina() {
        location.reload(); // Recarga la página actual
        }
         
    </script>
  </body>
</html>

SmartSparking/web/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>navbar Tres</title>
    <link rel="stylesheet" href="{% static '/css/index-login.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css' %}"
    />
  </head>

  <body>
    <header class="header">
      <div class="icono-menu">
        <img
          src="https://cdn.discordapp.com/attachments/759170694910705677/1120484064953110648/open-menu.png"
          id="icono-menu"
          alt="Logo de la marca"
        />
      </div>
      <div class="cont-menu active" id="menu">
        <ul>
          <li><a href="#">Support</a></li>
          <li><a href="#">Contact Us</a></li>
        </ul>
      </div>
      <nav>
        <ul class="nav-links">
          <button id="icono-back" class="btn-icon">
            <img
              src="https://cdn.discordapp.com/attachments/759170694910705677/1120491127343173672/back2.png"
              alt="Logo de la marca"
            />
          </button>
        </ul>
      </nav>
    </header>
    <div class="container">
      <div class="logi">
        <h2>SMART PARKING</h2>
        <div class="mensajito">
          {% if messages %}
          <ul class="messages">
            {% for message in messages %}
            <spam{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</spam>
            {% endfor %}
          </ul>
          {% else %}
          <p>Bienvenido Por favor ingrese datos para verifica tus credenciales.</p>
          {% endif %}
        </div>
        <form method="POST">
          {% csrf_token %}
          <label for="username">Correo:</label>
          <input type="text" id="username" name="username" />
          <label for="password">Clave:</label>
          <input type="password" id="password" name="password" /><br>
          <button type="submit">Login</button>
        </form>
       
      </div>

      <div class="autos">
        <img
          src="https://cdn.discordapp.com/attachments/759170694910705677/1120484063577387078/auto3.png"
          alt="autoport"
        />
      </div>
    </div>
    <script>
      
      document.getElementById("icono-back").addEventListener("click", function () {
        history.back();
      });

      const iconoMenu = document.querySelector("#icono-menu");
      const menu = document.querySelector("#menu");

      iconoMenu.addEventListener("click", (e) => {
        // Alternamos estilos para el menú body
        menu.classList.toggle("active");
        document.body.classList.toggle("opacity");

        // Alternamos su atributo 'src' para que el icono de menú cambie
        const rutaActual = e.target.getAttribute("src");

        if (
          rutaActual ==
          "https://cdn.discordapp.com/attachments/759170694910705677/1120484064953110648/open-menu.png"
        ) {
          e.target.setAttribute(
            "src",
            "https://cdn.discordapp.com/attachments/759170694910705677/1120484065150251058/open-menu2.png"
          );
        } else {
          e.target.setAttribute(
            "src",
            "https://cdn.discordapp.com/attachments/759170694910705677/1120484064953110648/open-menu.png"
          );
        }
      });
    </script>
  </body>
</html>